--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

---------------------------------------------------------------------
--                       TABLAS DE NEGOCIO                         --
---------------------------------------------------------------------

-- users ------------------------------------------------------------
CREATE TABLE public.users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password  VARCHAR(255) NOT NULL,
    role      VARCHAR(255),
    username  VARCHAR(255) NOT NULL UNIQUE,
    email     VARCHAR(255) NOT NULL UNIQUE
);
--ALTER TABLE public.users OWNER TO filehashuser;

-- file_hashes ------------------------------------------------------
CREATE TABLE public.file_hashes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    file_name  VARCHAR(255),
    sha256     VARCHAR(255),
    user_id    BIGINT NOT NULL,
    CONSTRAINT fk_filehash_user
        FOREIGN KEY (user_id) REFERENCES public.users(id)
);
--ALTER TABLE public.file_hashes OWNER TO filehashuser;

---------------------------------------------------------------------
--      Por eso se ha retirado cualquier CREATE/INSERT aquí         --
---------------------------------------------------------------------

-- PostgreSQL database dump complete
